In [10]:
import pandas as pd
import os

In [11]:
pwd = os.getcwd()
pwd

'c:\\Users\\kibeeen\\Documents\\GitHub\\pierre'

In [16]:
dataset = pd.read_excel(pwd + '\\Data - Homestead Data Skill Test..xlsx', sheet_name='data')
dataset

,Date,Platform (Northbeam),Name,Status,Medium,Source,Spend,Attributed Rev (1d),LTV Attributed Rev,Forecasted Attributed Rev (30d),...,LTV Transactions,Forecasted Attributed Transactions (30d),Forecasted Attributed Transactions (60d),Forecasted Attributed Transactions (90d),Email Signups (1d),LTV Email Signups,Email Signup Rate (1d),LTV Email Signup Rate,Cost per Email Signup (1d),LTV Cost per Email Signup
0,2022-11-26,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,517.530000,342.4250,342.4250,342.904505,...,2.750000,2.753759,2.797963,2.817787,8.000000,8.000000,0.065574,0.065574,64.691250,64.691250
1,2022-11-27,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,555.820000,207.2200,345.7000,346.402255,...,2.500000,2.504960,2.545530,2.563725,7.500000,7.500000,0.065789,0.065789,74.109333,74.109333
2,2022-11-28,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,540.560000,263.9700,263.9700,265.556109,...,1.500000,1.510491,1.548336,1.565310,2.000000,2.000000,0.017699,0.017699,270.280000,270.280000
3,2022-11-29,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,523.920001,81.9100,81.9100,84.156071,...,0.500000,0.516178,0.560684,0.580645,9.500000,9.500000,0.070896,0.070896,55.149474,55.149474
4,2022-11-30,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,509.619999,229.6225,285.6225,288.601927,...,1.583333,1.606053,1.662670,1.688062,7.083333,7.083333,0.045699,0.045699,71.946353,71.946353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,2022-12-20,Organic Search,Referral: google.co.kr,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1489,2022-12-20,Google Ads,arb_ga_elm_md_pmx_us_urlx,NaN,cpc,google,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1490,2022-12-21,Other,Referral: qq.com,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1491,2022-12-22,Organic Search,Referral: google.com.ar,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1492,2022-12-23,Organic Search,Referral: google.com.co,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN

In [17]:
dataset_modified = dataset.copy()
dataset_modified

,Date,Platform (Northbeam),Name,Status,Medium,Source,Spend,Attributed Rev (1d),LTV Attributed Rev,Forecasted Attributed Rev (30d),...,LTV Transactions,Forecasted Attributed Transactions (30d),Forecasted Attributed Transactions (60d),Forecasted Attributed Transactions (90d),Email Signups (1d),LTV Email Signups,Email Signup Rate (1d),LTV Email Signup Rate,Cost per Email Signup (1d),LTV Cost per Email Signup
0,2022-11-26,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,517.530000,342.4250,342.4250,342.904505,...,2.750000,2.753759,2.797963,2.817787,8.000000,8.000000,0.065574,0.065574,64.691250,64.691250
1,2022-11-27,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,555.820000,207.2200,345.7000,346.402255,...,2.500000,2.504960,2.545530,2.563725,7.500000,7.500000,0.065789,0.065789,74.109333,74.109333
2,2022-11-28,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,540.560000,263.9700,263.9700,265.556109,...,1.500000,1.510491,1.548336,1.565310,2.000000,2.000000,0.017699,0.017699,270.280000,270.280000
3,2022-11-29,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,523.920001,81.9100,81.9100,84.156071,...,0.500000,0.516178,0.560684,0.580645,9.500000,9.500000,0.070896,0.070896,55.149474,55.149474
4,2022-11-30,Facebook Ads,02_Prospecting_$LC_Testing_ABO,Active,NaN,NaN,509.619999,229.6225,285.6225,288.601927,...,1.583333,1.606053,1.662670,1.688062,7.083333,7.083333,0.045699,0.045699,71.946353,71.946353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,2022-12-20,Organic Search,Referral: google.co.kr,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1489,2022-12-20,Google Ads,arb_ga_elm_md_pmx_us_urlx,NaN,cpc,google,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1490,2022-12-21,Other,Referral: qq.com,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1491,2022-12-22,Organic Search,Referral: google.com.ar,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1492,2022-12-23,Organic Search,Referral: google.com.co,NaN,NaN,NaN,NaN,0.0000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN

In [23]:
dataset.columns

columns_to_drop = [
    'Date', 'Name', 'Status', 'Medium', 'Source',
    'LTV Attributed Rev',
    'Forecasted Attributed Rev (30d)',
    'Forecasted Attributed Rev (60d)',
    'Forecasted Attributed Rev (90d)',
    'ROAS (1d)', 'LTV ROAS',
    'Forecasted ROAS (30d)', 
    'Forecasted ROAS (60d)',
    'Forecasted ROAS (90d)',
    'CTR', 'eCPC', 'CPM',
    'ECR (1d)', 'LTV ECR',
    'CAC (1d)', 'LTV CAC',
    'LTV Transactions',
    'Forecasted Attributed Transactions (30d)',
    'Forecasted Attributed Transactions (60d)',
    'Forecasted Attributed Transactions (90d)',
    'LTV Email Signups',
    'Email Signup Rate (1d)',
    'LTV Email Signup Rate',
    'Cost per Email Signup (1d)',
    'LTV Cost per Email Signup'
]

In [24]:
dataset_modified = dataset_modified.drop(columns=columns_to_drop)
dataset_modified

,Platform (Northbeam),Spend,Attributed Rev (1d),Imprs,Visits,New Visits,Transactions (1d),Email Signups (1d)
0,Facebook Ads,517.530000,342.4250,18038.0,146.0,122.0,2.750000,8.000000
1,Facebook Ads,555.820000,207.2200,22704.0,134.0,114.0,1.500000,7.500000
2,Facebook Ads,540.560000,263.9700,20816.0,125.0,113.0,1.500000,2.000000
3,Facebook Ads,523.920001,81.9100,22440.0,147.0,134.0,0.500000,9.500000
4,Facebook Ads,509.619999,229.6225,26026.0,187.0,155.0,1.083333,7.083333
...,...,...,...,...,...,...,...,...
1488,Organic Search,NaN,0.0000,NaN,1.0,1.0,0.000000,0.000000
1489,Google Ads,NaN,0.0000,NaN,1.0,1.0,0.000000,0.000000
1490,Other,NaN,0.0000,NaN,3.0,2.0,0.000000,0.000000
1491,Organic Search,NaN,0.0000,NaN,1.0,1.0,0.000000,0.000000
1492,Organic Search,NaN,0.0000,NaN,1.0,1.0,0.000000,0.000000

In [25]:
dataset_modified.columns

Index(['Platform (Northbeam)', 'Spend', 'Attributed Rev (1d)', 'Imprs',
       'Visits', 'New Visits', 'Transactions (1d)', 'Email Signups (1d)'],
      dtype='object')